version: "362"

services:
  nginx:
    image: nginx:1.19
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dockerfile/dev/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./dockerfile/dev/nginx/cert.pem:/etc/nginx/ssl/cert.pem
      - ./dockerfile/dev/nginx/key.pem:/etc/nginx/ssl/key.pem
    tmpfs:
      - /run
      - /var/run
      - /tmp
      - /var/cache/nginx

  front:
    image: node:16.13.0
    stdin_open: true
    restart: unless-stopped
    working_dir: /usr/src/app/
    env_file:
      - .env.local
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: >
      sh -c "npm i && npm run dev"

volumes:
  node_modules:
  db_local_data:
